"""Database client package."""
from .client import (
    get_beurer_supabase,
    content_hash,
    item_exists,
    save_social_item,
    create_crawler_run,
    update_crawler_run,
    get_items_without_embeddings,
    update_item_embedding,
    search_by_embedding,
    get_item_count,
    get_items_needing_date_fix,
    update_item_posted_at,
    get_embedding_count,
    save_answers,
    get_answers_for_item,
    update_item_qa_metadata,
    get_items_without_answers,
    save_item_entities,
    save_item_aspects,
)

__all__ = [
    "get_beurer_supabase",
    "content_hash",
    "item_exists",
    "save_social_item",
    "create_crawler_run",
    "update_crawler_run",
    "get_items_without_embeddings",
    "update_item_embedding",
    "search_by_embedding",
    "get_item_count",
    "get_items_needing_date_fix",
    "update_item_posted_at",
    "get_embedding_count",
    "save_answers",
    "get_answers_for_item",
    "update_item_qa_metadata",
    "get_items_without_answers",
    "save_item_entities",
    "save_item_aspects",
]
